[package]
name = "render"
version = "0.1.0"
authors = ["SamokhinIlya <samokhin.ilya.97@gmail.com>"]
edition = "2018"

[dependencies]
utils = { path = "../../utils" }
platform = { path = "../../platform" }